### PR TITLE
Reduce missing close quote false positives

### LINKED ISSUE #218: False positives for missing close quotes
I was looking at some false positives for missing close quotes, and considering adjusting the detection somewhat. I'm unsure if there are situations where a multi-line quote is always invalid, but there are a number of valid cases I'm aware of.

```
"ai_ideological_opinion(
c:GBR
)" > 0
```
```
debug_log = "line1
line2
line3"
```
```
my_scripted_trigger = {
 parameter_with_multiple_lines = "
   add = 1
   multiply = 2
 "
}
```

I found the following note on a related issue

> Technically it's easy :) The parser already looks for the closing quote over multiple lines. We would just have to delete the warning.
> 
> It's just that this warning is very helpful if you accidentally leave out a closing quote, so I hate to lose it. The vast majority of quoted strings are intended to be only one line. I wonder if there's a heuristic that would let the parser detect that intent.
> 
> Without this warning... Since most files have multiple quoted strings, the parser will usually find a quote mark to pair up with (namely the one starting the next quoted string), all the way to the end of the file where it will emit an unexpected eof warning. Unless you forgot TWO closing quotes, in which case it will silently mismatch them. You'll probably get other validation errors, but none of them will say "hey you forgot to close the string on this line". 

 _Originally posted by @amtep in [#164](https://github.com/amtep/tiger/issues/164#issuecomment-2629665702)_

In order to preserve the useful cases for the missing close quote, what if the parser looked for situations that look like the quote should be an opening one, but is actually closing a block, then returns to the line with the opening quote and warns there.

Example 1:
```
debug_log = "oops I forgot a close quote
debug_log = "oops this opening quote is actually a close quote"
```
In this situation, '=' followed by a quote is an indication that the quote *should* be an opener, not a closer

Example 2:
```
OR = {
   "ai_ideological_opinion(
      c:GBR
   ) > 0
   "ai_ideological_opinion(
      c:FRA
   )" > 0
}
```
Close quote followed by a trigger instead of a comparator or or new line is an indication that this should be an opening quote, not a closing one

### PR DESCRIPTION
**Pull request by BrknRobot**
Closes #218

Rather than warning on every multi-line quote, this looks for two cases which would indicate the close quote was intended to be an opener.

Previous non-whitespace character was a comparator:
```
a = "
b = ""
```

Previous non-whitespace character was a close brace followed by whitespace:
```
a = "b(c)
"b(c)" = a
```

I've included as many test cases of matched and unmatched quotes as I could think of, but feel free to provide more if there's some combinations of syntax I've missed.

This removes two false positives from the vanilla victoria 3 scripts

### CODE REVIEW

File: src/parse/pdxfile/lexer.rs [hunk 1]
```diff
@@ -462,20 +476,22 @@ impl Iterator for Lexer<'_> {
...
                             }
                             id.add_char(c);
-                            if warn_linebreaks {
-                                // Warn, but continue parsing the string.
-                                let msg = "quoted string not closed";
-                                warn(ErrorKey::ParseError).weak().msg(msg).loc(self.loc).push();
-                            }
                             self.consume();
-                        } else if Game::is_hoi4() && c == '\\' && !escaped {
+                        } else if c == '\\' && !escaped {
```
Comment (amtep) [inline src/parse/pdxfile/lexer.rs:480]: Are you sure about removing the `is_hoi4`? Hoi4 has a different string processor. I'm not aware of the other games having escaping.

File: src/parse/pdxfile/lexer.rs [hunk 2]
```diff
@@ -442,14 +442,28 @@ impl Iterator for Lexer<'_> {
...
+                            expect_open = true;
+                        } else if !c.is_ascii_whitespace() && c != '"' {
+                            expect_open = false;
+                        }
+
+                        if c == ')' {
+                            // Whitespace is not allowed after the closing broce of a quoted trigger
+                            // We should expect to close the quote on the next character or warn
+                            expect_immediate_close = true;
+                        } else if expect_immediate_close && c.is_ascii_whitespace() {
```
Comment (amtep) [inline src/parse/pdxfile/lexer.rs:462]: This might inappropriately trigger in quoted gui datatype expressions, which can have sequences like `)) )` when closing lots of nested parentheses.

File: tests/files/mod3/common/on_action/test-unmatched-matched-trigger.txt [hunk 3]
```diff
@@ -0,0 +1,10 @@
+﻿yearly_playable_pulse = {
+    effect = {
+        if = {
+            limit = {
+                0 < "opinion(liege)
```
Comment (amtep) [inline tests/files/mod3/common/on_action/test-unmatched-matched-trigger.txt:5]: If this were `"opinion(liege) < 0` it wouldn't catch it, right?

File: src/parse/pdxfile/lexer.rs (hunk 1 above)
Comment (BrknRobot) [reply src/parse/pdxfile/lexer.rs:480]: I've tested Vic3 and CK3. Both worked as expected when escaping quotes. I don't own Imperator to test.

File: src/parse/pdxfile/lexer.rs (hunk 2 above)
Comment (BrknRobot) [reply src/parse/pdxfile/lexer.rs:462]: I'm not as familiar with gui and loc. Do you have some examples that should and should not warn I can add to the test cases?

File: tests/test.rs [hunk 4]
```diff
@@ -159,3 +192,29 @@ fn test_mod2() {
...
+    let report =
+        take_report_pointer(&mut reports, after_comparitor, "quoted string not closed", 3, 21);
+    report.expect("unmatched quote matched after comparitor test");
+    ignore_reports(&mut reports, after_comparitor);
+
+    let before_comparitor = "common/on_action/test-unmatched-matched-trigger.txt";
+    let report =
+        take_report_pointer(&mut reports, before_comparitor, "quoted string not closed", 5, 21);
+    report.expect("unmatched quote matched before comparitor test");
+    ignore_reports(&mut reports, before_comparitor);
```
[the remark this answers is not in the document]
Comment (BrknRobot) [reply tests/test.rs]: Whoops

File: src/parse/pdxfile/lexer.rs [hunk 5]
```diff
@@ -462,20 +476,22 @@ impl Iterator for Lexer<'_> {
...
                             self.consume();
                             id.make_owned();
                             escaped = true;
                             continue;
                         } else if c == '"' && !escaped {
                             let token = id.take_to_token();
                             self.consume();
+
+                            // Previous characters indicate that this could have been intended to be an opening quote
+                            if expect_open || immediate_close_warn {
```
[the remark this answers is not in the document]
Comment (BrknRobot) [reply src/parse/pdxfile/lexer.rs:490]: A `)"` is correct and should not warn, ') "' is incorrect and should warn.
`expect_immediate_close` assumes `)` is the closing parenthesis of a complex trigger, and indicates the next character should be `"`.
`immediate_close_warn` indicates we were expecting to close the quote but found whitespace, indicating we should issue a warning.
Both fields get reset if we find any other character, and we assume that `)` was part of a text string, not a complex trigger.

`"a(b) "` -> Looks like complex trigger, warn
`"this (is just a) string" -> Doesn't look like a complex trigger, don't warn
`":) "` -> This emoji looks like a complex trigger, warn, but it's a false positive

File: src/parse/pdxfile/lexer.rs (hunk 2 above)
Comment (amtep) [reply src/parse/pdxfile/lexer.rs:462]: Localization has its own parser and the format is fully line based, so all line breaks in loca strings have to be `\n`. No need to worry about it here.

Comment (BrknRobot) [reply src/parse/pdxfile/lexer.rs]: I've added those as test cases

File: src/parse/pdxfile/lexer.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (BrknRobot) [reply src/parse/pdxfile/lexer.rs]: > I don't think it should say "quoted string not closed" when there's a closing quote on the same line.
I can add a check for new lines. This will catch some cases where multiple quotes are missing on a single line, but relying on other error checking might be good enough

> The complex trigger check feels like it should be checked at a higher level
I've replaced the logic with something a bit more general that's not looking for complex triggers specifically. It may still warn if there's a trailing space in the triggers quotes though.

> A better check at the string level might be to warn if the closing quote is immediately followed by a non-whitespace character.
I had already been considering look ahead logic but took it out when it ended up not being required for any of my original test cases. With the new test cases, I'm relying on one character of look behind, and one character of look ahead. But I do have some code stashed locally that looks ahead a bit further if it ends up being necessary. I'd like to avoid looking ahead over non-whitespace if we can help it though

**Review by amtep — APPROVED** [review]
